version: '3'
services:
  dev:
    build:
      context: docker/dev
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mysql
    env_file:
      - .env.docker
  mysql:
    image: mysql:8
    env_file:
      - .env
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "127.0.0.1:3306:3306"
